--- #YAML:1.0
name:               Proc-Forking
version:            1.45
abstract:           Proc::Forking - fork a function and daemonize the parent
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cwd:        0
    IO::File:   0
    POSIX:      0
    Sys::Load:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
